/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExtendedUserProfile {
  'principal' : Principal,
  'name' : string,
  'photo' : [] | [ProfilePhoto],
  'college' : string,
}
export interface Note {
  'id' : bigint,
  'likeCount' : bigint,
  'owner' : Principal,
  'isStarred' : boolean,
  'year' : string,
  'answer' : string,
  'author' : string,
  'questionText' : string,
  'questionNo' : string,
  'isPinned' : boolean,
  'college' : string,
}
export interface NoteLiker {
  'principal' : Principal,
  'name' : string,
  'college' : string,
}
export interface ProfilePhoto { 'data' : Uint8Array, 'mimeType' : string }
export interface UserProfile {
  'name' : string,
  'photo' : [] | [ProfilePhoto],
  'college' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<
    [string, string, string, string, string, string, boolean, boolean],
    bigint
  >,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserRole' : ActorMethod<[], UserRole>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNoteLikers' : ActorMethod<[bigint], Array<NoteLiker>>,
  'getNotesByQuestionNo' : ActorMethod<[string], Array<Note>>,
  'getUserNotesByCollege' : ActorMethod<[string], Array<Note>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeNote' : ActorMethod<[bigint], undefined>,
  'listAllUsers' : ActorMethod<[], Array<ExtendedUserProfile>>,
  'listNotesSortedByQuestionNo' : ActorMethod<[], Array<Note>>,
  'reportAndDeleteNote' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleStarPin' : ActorMethod<[bigint, boolean, boolean], undefined>,
  'updateNote' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];