/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'college' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'owner' : IDL.Principal,
  'isStarred' : IDL.Bool,
  'year' : IDL.Text,
  'answer' : IDL.Text,
  'author' : IDL.Text,
  'questionText' : IDL.Text,
  'questionNo' : IDL.Text,
  'isPinned' : IDL.Bool,
  'college' : IDL.Text,
});
export const NoteLiker = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'college' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNoteLikers' : IDL.Func([IDL.Nat], [IDL.Vec(NoteLiker)], ['query']),
  'getNotesByQuestionNo' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getUserNotesByCollege' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeNote' : IDL.Func([IDL.Nat], [], []),
  'listNotesSortedByQuestionNo' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleStarPin' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Bool], [], []),
  'updateNote' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'college' : IDL.Text });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'owner' : IDL.Principal,
    'isStarred' : IDL.Bool,
    'year' : IDL.Text,
    'answer' : IDL.Text,
    'author' : IDL.Text,
    'questionText' : IDL.Text,
    'questionNo' : IDL.Text,
    'isPinned' : IDL.Bool,
    'college' : IDL.Text,
  });
  const NoteLiker = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'college' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNoteLikers' : IDL.Func([IDL.Nat], [IDL.Vec(NoteLiker)], ['query']),
    'getNotesByQuestionNo' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getUserNotesByCollege' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeNote' : IDL.Func([IDL.Nat], [], []),
    'listNotesSortedByQuestionNo' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleStarPin' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Bool], [], []),
    'updateNote' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };